FROM mcr.microsoft.com/devcontainers/javascript-node:20

RUN npm install -g npm@latest

WORKDIR /workspaces

# Install any additional OS packages if needed
# RUN apt-get update && apt-get install -y <package-name>

CMD ["bash"]
